require 'rake/testtask'

Rake::TestTask.new(:test) do |t|
  t.libs << 'test'
  t.libs << 'app'
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

task default: :test

desc "Run all tests"
task :test_all do
  sh 'ruby -Itest test/models/pillbox_test.rb'
  sh 'ruby -Itest test/models/compartment_test.rb'
  sh 'ruby -Itest test/models/compartment_medication_test.rb'
end

desc "Run model tests"
task :test_models do
  sh 'ruby -Itest test/models/pillbox_test.rb'
  sh 'ruby -Itest test/models/compartment_test.rb'
  sh 'ruby -Itest test/models/compartment_medication_test.rb'
end

desc "Run pillbox model tests"
task :test_pillbox do
  sh 'ruby -Itest test/models/pillbox_test.rb'
end

desc "Run compartment model tests"
task :test_compartment do
  sh 'ruby -Itest test/models/compartment_test.rb'
end

desc "Run compartment medication model tests"
task :test_compartment_medication do
  sh 'ruby -Itest test/models/compartment_medication_test.rb'
end
